title: "Personal Webpage"
name: "[Your Name]"
description: "I am a professor specializing in financial statistical methods, machine learning, and wealth management."
email: "your-email@example.com"
github_username: "venteng"
linkedin: "https://www.linkedin.com/in/your-profile"
